#pragma once
#include <stdio.h>
#include <tchar.h>
#define _USE_MATH_DEFINES
#include <math.h>
#include <assert.h>
#include <stdlib.h>
//#include <../../glm/glm/ext/matrix_clip_space.hpp>
#include <D:/ycheba/CG/lab7/glm/glm/ext/matrix_clip_space.hpp>
//#include <../../glm/glm/ext/matrix_transform.hpp>
#include <D:/ycheba/CG/lab7/glm/glm/ext/matrix_transform.hpp>
//#include <../../glm/glm/ext.hpp>
#include <D:/ycheba/CG/lab7/glm/glm/ext.hpp>
#define GLEW_STATIC
#include <glew.h>
#include "glut.h"
#include <Windows.h>
#include <GdiPlus.h>
#include <stdexcept>
#include <set>
#include <numbers>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <sstream>
#include <fstream>
